schema_version = "1.0.0"
id = "BsMax"
name = "BsMax"
version = "1.2.20240701"
tagline = "Keymap/ UISimulator and ManyTools"
maintainer = "Naser Merati(Nevil) <Nevilart@Gmail.Com>"
type = "add-on"
tags = ["Curves", "Rigg", "Animation", "Sequencer", "Keymap"]
blender_version_min = "4.2.0"
blender_version_max = "5.0.0"
license = ["SPDX:GPL-2.0-or-later"]
website = "https://github.com/NevilArt/BsMax"