############################################################################
#	This program is free software: you can redistribute it and/or modify
#	it under the terms of the GNU General Public License as published by
#	the Free Software Foundation, either version 3 of the License, or
#	(at your option) any later version.
#
#	This program is distributed in the hope that it will be useful,
#	but WITHOUT ANY WARRANTY; without even the implied warranty of
#	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#	GNU General Public License for more details.
#
#	You should have received a copy of the GNU General Public License
#	along with this program.  If not, see <https://www.gnu.org/licenses/>.
############################################################################


c0000="object.select_linked(type='OBDATA')"
c0001="object.convert_to(target='MESH')"
c0002="object.convert_to(target='CURVE')"
c0003="wm.tool_set_by_id(name='builtin.move')"
c0004="object.tti_call(switch='move')"
c0005="wm.tool_set_by_id(name='builtin.rotate')"
c0006="object.tti_call(switch='rotate')"
c0007="wm.tool_set_by_id(name='builtin.scale')"
c0008="object.tti_call(switch='scale')"
c0009="wm.tool_set_by_id(name='builtin.select_box')"
c0010="object.select_similar()"
c0011="object.clone('FAULT')"
c0012="object.hide(mode='selection')"
c0013="object.hide(mode='unselected')"
c0014="object.hide(mode='clear', collection=True)"
c0015="object.freeze(mode='SELECTION')"
c0016="object.freeze(mode='CLEAR')"
c0017="view3d.localview('INVOKE_DEFAULT')"
c0018="object.subobject_level(level=6)"
c0019="object.subobject_level(level=1)"
c0020="object.subobject_level(level=2)"
c0021="object.subobject_level(level=3)"
c0022="object.subobject_level(level=4)"
c0023="object.subobject_level(level=5)"
c0024="screen.repeat_last()"
c0025="wm.tool_set_by_id(name='builtin.bisect')"
c0026="mesh.knife_tool('INVOKE_DEFAULT')"
c0027="mesh.edge_collapse()"
c0028="mesh.hide(unselected=True)"
c0029="view3d.toggle_xray()"
c0030="curve.handle_type_set(type='AUTOMATIC')"
c0031="curve.handle_type_set(type='VECTOR')"
c0032="curve.handle_type_set(type='ALIGNED')"
c0033="curve.handle_type_set(type='FREE_ALIGN')"
c0034="curve.subdivide()"
c0035="wm.tool_set_by_id(name='builtin.poly_build')"
c0036="mesh.dissolve_verts()"
c0037="mesh.separate()"
c0038="mesh.connect()"
c0039="wm.tool_set_by_id(name='builtin.extrude_region')"
c0040="mesh.chamfer()"
c0041="mesh.weld('INVOKE_DEFAULT')"
c0042="wm.call_menu(name='VIEW3D_MT_edit_mesh_weld')"
c0043="mesh.dissolve_edges()"
c0044="object.paths_calculate('INVOKE_DEFAULT')"
c0045="mesh.subdivide()"
c0046="wm.tool_set_by_id(name='builtin.extrude_region')"
c0047="wm.tool_set_by_id(name='builtin.bevel')"
c0048="mesh.subdivide_edgering()"
c0049="mesh.create_curve_from_edge()"
c0050="mesh.dissolve_faces()"
c0051="mesh.detach('INVOKE_DEFAULT')"
c0052="wm.tool_set_by_id(name='builtin.extrude_region')"
c0053="wm.tool_set_by_id(name='builtin.inset_faces')"
c0054="mesh.flip_normals()"
c0055="curve.chamfer('INVOKE_DEFAULT')"
c0056="curve.chamfer('INVOKE_DEFAULT', fillet=True)"
c0057="light.set_type(mode='POINT')"
c0058="light.set_type(mode='SUN')"
c0059="light.set_type(mode='SPOT')"
c0060="light.set_type(mode='AREA')"
c0061="light.setting(name='SHADOW')"
c0062="create.sphere('INVOKE_DEFAULT')"
c0063="create.box('INVOKE_DEFAULT')"
c0064="create.cylinder('INVOKE_DEFAULT')"
c0065="create.plane('INVOKE_DEFAULT')"
c0066="create.line('INVOKE_DEFAULT')"
c0067="create.circle('INVOKE_DEFAULT')"
c0068="create.rectangle('INVOKE_DEFAULT')"
c0069="create.arc('INVOKE_DEFAULT')"
c0070="view3d.view_axis(type='FRONT')"
c0071="view3d.view_axis(type='BACK')"
c0072="view3d.view_axis(type='TOP')"
c0073="view3d.view_axis(type='BOTTOM')"
c0074="view3d.view_axis(type='LEFT')"
c0075="view3d.view_axis(type='RIGHT')"
c0076="view3d.view_persportho()"
c0077="camera.set_active()"
c0078="camera.create_from_view()"
c0079="anim.set_key()"
c0080="anim.set_key_filters('INVOKE_DEFAULT')"
c0081="anim.keyframe_clear_v3d_plus()"
c0082="object.coordinate_system(coordsys='CURSOR')"
c0083="object.coordinate_system(coordsys='LOCAL')"
c0084="object.coordinate_system(coordsys='NORMAL')"
c0085="object.coordinate_system(coordsys='GIMBAL')"
c0086="object.coordinate_system(coordsys='VIEW')"
c0087="object.coordinate_system(coordsys='GLOBAL')"
c0088="object.snap_setting(mode='INCREMENT')"
c0089="object.snap_setting(mode='VERTEX')"
c0090="object.snap_setting(mode='VOLUME')"
c0091="object.snap_setting(mode='EDGE')"
c0092="object.snap_setting(mode='FACE')"
c0093="object.snap_setting(mode='CLOSEST')"
c0094="object.snap_setting(mode='CENTER')"
c0095="object.snap_setting(mode='MEDIAN')"
c0096="object.snap_setting(mode='ACTIVE')"
c0097="render.render('INVOKE_DEFAULT')"
c0098="mesh.attach('INVOKE_DEFAULT')"
c0099="mesh.attach_list('INVOKE_DEFAULT')"
c0100="object.quick_smoke()"
c0101="object.quick_fur()"
c0102="object.quick_explode()"
c0103="object.quick_fluid()"
c0104="object.origin_set(type='GEOMETRY_ORIGIN', center='MEDIAN')"
c0105="object.origin_set(type='ORIGIN_GEOMETRY', center='MEDIAN')"
c0106="object.origin_set(type='ORIGIN_CURSOR', center='MEDIAN')"
c0107="object.origin_set(type='ORIGIN_CENTER_OF_VOLUME', center='MEDIAN')"
c0108="object.origin_set(type='ORIGIN_CENTER_OF_MASS', center='MEDIAN')"
c0109="wm.tool_set_by_id(name='builtin.cursor')"
c0110="object.snap_setting(mode='MOVE')"
c0111="object.snap_setting(mode='ROTATE')"
c0112="object.snap_setting(mode='SCALE')"
c0113="render.set_renderer(name='BLENDER_EEVEE')"
c0114="render.set_renderer(name='BLENDER_WORKBENCH')"
c0115="render.set_renderer(name='CYCLES')"
c0116="render.setting_toggle(name='use_gtao')"
c0117="render.setting_toggle(name='use_bloom')"
c0118="render.setting_toggle(name='use_ssr')"
c0119="render.setting_toggle(name='use_motion_blur')"
c0120="render.setting_toggle(name='use_simplify')"
c0121="render.setting_toggle(name='use_freestyle')"
c0122="render.setting_toggle(name='use_curves')"
c0123="render.setting_toggle(name='show_backface_culling')"
c0124="render.setting_toggle(name='use_motion_blur')"
c0125="render.setting_toggle(name='show_xray')"
c0126="render.setting_toggle(name='show_shadows')"
c0127="render.setting_toggle(name='show_cavity')"
c0128="render.setting_toggle(name='use_dof')"
c0129="render.setting_toggle(name='show_object_outline')"
c0130="mesh.target_weld('INVOKE_DEFAULT')"
c0131="camera.create_target()"
c0132="camera.clear_targte()"
c0133="camera.select('INVOKE_DEFAULT')"
c0134="create.extrude()"
c0135="mesh.remove_isolated_geometry()"
c0136="object.set_local_coord_in_pose_mode()"
c0137="camera.lock_to_view_toggle()"
c0138="camera.select_active_camera(selcam=True, seltrg=False)"
c0139="camera.select_active_camera(selcam=False, seltrg=True)"
c0140="camera.select_active_camera(selcam=True, seltrg=True)"
c0141="light.create_target()"
c0142="light.clear_target()"
c0143="mesh.bridge_edge_loops(twist_offset=0)"
c0144="object.align_selected_to_target('INVOKE_DEFAULT')"
c0145="curve.chamfer('INVOKE_DEFAULT', typein=True)"
c0146="curve.chamfer('INVOKE_DEFAULT', fillet=True, typein=True)"
c0147="camera.select_target()"
c0148="armature.bone_devide('INVOKE_DEFAULT')"
c0149="armature.bone_devide('INVOKE_DEFAULT', typein=True)"
c0150="armature.bone_type(mode='OCTAHEDRAL')"
c0151="armature.bone_type(mode='STICK')"
c0152="armature.bone_type(mode='BBONE')"
c0153="armature.bone_type(mode='ENVELOPE')"
c0154="armature.bone_type(mode='WIRE')"
c0155="object.freeze_transform(location=True, rotation=True, scale=True)"
c0156="object.freeze_transform(location=False, rotation=True, scale=False)"
c0157="object.transform_to_zero(location=True, rotation=True, scale=True)"
c0158="object.transform_to_zero(location=False, rotation=True, scale=False)"
c0159="curve.dividplus('INVOKE_DEFAULT', typein=True)"
c0160="curve.switch_direction()"
c0161="curve.make_first()"
c0162="camera.lock_toggle(name='CAMERA')"
c0163="camera.lock_toggle(name='CURSOR')"
c0164="camera.lock_transform()"
c0165="mesh.edge_split()"
c0166="object.properties('INVOKE_DEFAULT')"
c0167="editor.float(ui_type='FCURVES')"
c0168="editor.float(ui_type='DOPESHEET')"
c0169="editor.float(ui_type='NLA_EDITOR')"
c0170="editor.float(ui_type='DRIVERS')"
c0171="editor.float(ui_type='TEXT_EDITOR')"
c0172="object.placment()"
c0173="object.link_to('INVOKE_DEFAULT')"
c0174="object.parent_clear(type='CLEAR_KEEP_TRANSFORM')"
c0175="view3d.setting(name='use_transform_skip_children')"
c0176="view3d.setting(name='WIREFRAME')"
c0177="view3d.setting(name='SOLID')"
c0178="view3d.setting(name='MATERIAL')"
c0179="view3d.setting(name='RENDERED')"
c0180="view3d.setting(name='COMBINED')"
c0181="view3d.setting(name='EMISSION')"
c0182="view3d.setting(name='ENVIRONMENT')"
c0183="view3d.setting(name='SHADOW')"
c0184="view3d.setting(name='DIFFUSE_LIGHT')"
c0185="view3d.setting(name='DIFFUSE_COLOR')"
c0186="view3d.setting(name='SPECULAR_LIGHT')"
c0187="view3d.setting(name='SPECULAR_COLOR')"
c0188="view3d.setting(name='VOLUME_TRANSMITTANCE')"
c0189="view3d.setting(name='VOLUME_SCATTER')"
c0190="view3d.setting(name='NORMAL')"
c0191="view3d.setting(name='MIST')"
c0192="view3d.setting(name='use_scene_lights_render')"
c0193="view3d.setting(name='use_scene_world_render')"
c0194="mesh.select_element_toggle()"
c0195="anim.keyframe_insert_menu('INVOKE_DEFAULT')"
c0196="pose.copy()"
c0197="pose.paste(flipped=False, selected_mask=False)"
c0198="pose.paste(flipped=True, selected_mask=False)"
c0199="pose.push('INVOKE_DEFAULT')"
c0200="pose.relax('INVOKE_DEFAULT')"
c0201="pose.breakdown('INVOKE_DEFAULT')"
c0202="pose.paths_calculate('INVOKE_DEFAULT')"
c0203="pose.paths_clear('INVOKE_DEFAULT')"
c0204="pose.hide(unselected=False)"
c0205="pose.hide(unselected=True)"
c0206="pose.reveal()"
c0207="pose.user_transforms_clear()"
c0208="curve.attach('INVOKE_DEFAULT')"
c0209="armature.attach('INVOKE_DEFAULT')"
c0210="object.attach('INVOKE_DEFAULT')"
c0211="curve.refine('INVOKE_DEFAULT')"
c0212="object.convert_to(target='GPENCIL')"
c0213="object.convert_to(target='CURVES')"
c0214="editor.float(ui_type='GeometryNodeTree')"
c0215="anim.path_constraint('INVOKE_DEFAULT')"
c0216="anim.location_constraint('INVOKE_DEFAULT')"
c0217="anim.link_constraint('INVOKE_DEFAULT')"
c0218="anim.link_to_world('INVOKE_DEFAULT')"
c0219="anim.lookat_constraint('INVOKE_DEFAULT')"
c0220="anim.orientation_constraint('INVOKE_DEFAULT')"
c0221="anim.freeze_on('INVOKE_DEFAULT')"
c0222="object.paths_update()"
c0223="wm.call_menu(name='VIEW3D_MT_viewlayer')"
c0224="mesh.nurms_toggle()"
c0225="mesh.quads_convert_to_tris()"
c0226="mesh.outline_offset('INVOKE_DEFAULT')"
c0227="mesh.mevel()"
c0228="pose.armature_apply(selected=False)"
c0229="pose.transforms_clear()"
c0230="wm.call_menu(name='Object_MT_Snap_Setting')"
c0231="mesh.hide_plus(mode='SELECTED')"
c0232="mesh.hide_plus(mode='UNSELECTED')"
c0233="mesh.hide_plus(mode='UNHIDE')"
c0234="curve.hide(unselected=False)"
c0235="curve.hide(unselected=True)"
c0236="curve.reveal()"
c0237="bone.freeze(mode='selection')"
c0238="bone.freeze(mode='unselected')"
c0239="bone.freeze(mode='clear')"
c0240="object.freeze(mode='UNSELECTED')"
c0241="object.coordinate_system(coordsys='PARENT')"
c0242=""
c0243=""
c0244=""
c0245=""
c0246=""
c0247=""
c0248=""
c0249=""
c0250=""