############################################################################
#	This program is free software: you can redistribute it and/or modify
#	it under the terms of the GNU General Public License as published by
#	the Free Software Foundation, either version 3 of the License, or
#	(at your option) any later version.
#
#	This program is distributed in the hope that it will be useful,
#	but WITHOUT ANY WARRANTY; without even the implied warranty of
#	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#	GNU General Public License for more details.
#
#	You should have received a copy of the GNU General Public License
#	along with this program.  If not, see <https://www.gnu.org/licenses/>.
############################################################################

c0000="bpy.ops.bsmax.clearprimitivedta('INVOKE_DEFAULT')"
c0001="bpy.ops.object.convert(target='MESH')"
c0002="bpy.ops.object.convert(target='CURVE')"
c0003="bpy.ops.wm.tool_set_by_id(name='builtin.move')"
c0004="bpy.ops.bsmax.transformtypein('INVOKE_DEFAULT')"
c0005="bpy.ops.wm.tool_set_by_id(name='builtin.rotate')"
c0006="bpy.ops.bsmax.transformtypein('INVOKE_DEFAULT')"
c0007="bpy.ops.wm.tool_set_by_id(name='builtin.scale')"
c0008="bpy.ops.bsmax.transformtypein('INVOKE_DEFAULT')"
c0009="bpy.ops.wm.tool_set_by_id(name='builtin.select_box')"
c0010="bpy.ops.bsmax.selectsimilar('INVOKE_DEFAULT')"
c0011="bpy.ops.bsmax.cloneselectedobjects('INVOKE_DEFAULT')"
c0012="bpy.ops.object.hide_view_set('INVOKE_DEFAULT')"
c0013="bpy.ops.object.hide_view_set(unselected=True)"
c0014="bpy.ops.object.hide_view_clear('INVOKE_DEFAULT')"
c0015="bpy.ops.bsmax.freezeselectedobjects('INVOKE_DEFAULT')"
c0016="bpy.ops.bsmax.unfreezeallobjects('INVOKE_DEFAULT')"
c0017="bpy.ops.view3d.localview('INVOKE_DEFAULT')"
c0018="bpy.ops.bsmax.subobjectlevel(level=6)"
c0019="bpy.ops.bsmax.subobjectlevel(level=1)"
c0020="bpy.ops.bsmax.subobjectlevel(level=2)"
c0021="bpy.ops.bsmax.subobjectlevel(level=3)"
c0022="bpy.ops.bsmax.subobjectlevel(level=4)"
c0023="bpy.ops.bsmax.subobjectlevel(level=5)"
c0024="bpy.ops.screen.repeat_last('INVOKE_DEFAULT')"
c0025="bpy.ops.wm.tool_set_by_id(name='builtin.bisect')"
c0026="bpy.ops.mesh.knife_tool('INVOKE_DEFAULT')"
c0027="bpy.ops.mesh.edge_collapse('INVOKE_DEFAULT')"
c0028="bpy.ops.mesh.hide(unselected=True)"
c0029="bpy.ops.view3d.toggle_xray('INVOKE_DEFAULT')"
c0030="bpy.ops.curve.handle_type_set(type='AUTOMATIC')"
c0031="bpy.ops.curve.handle_type_set(type='VECTOR')"
c0032="bpy.ops.curve.handle_type_set(type='ALIGNED')"
c0033="bpy.ops.curve.handle_type_set(type='FREE_ALIGN')"
c0034="bpy.ops.curve.subdivide('INVOKE_DEFAULT')"
c0035="bpy.ops.wm.tool_set_by_id(name='builtin.poly_build')"
c0036="bpy.ops.mesh.dissolve_verts('INVOKE_DEFAULT')"
c0037="bpy.ops.mesh.separate('INVOKE_DEFAULT')"
c0038="bpy.ops.bsmax.connectpoly('INVOKE_DEFAULT')"
c0039="bpy.ops.wm.tool_set_by_id(name='builtin.extrude_region')"
c0040="bpy.ops.wm.tool_set_by_id(name='builtin.bevel')"
c0041="bpy.ops.mesh.remove_doubles(threshold=1.0,use_unselected=False)"
c0042="bpy.ops.mesh.remove_doubles('INVOKE_DEFAULT')"
c0043="bpy.ops.mesh.dissolve_edges('INVOKE_DEFAULT')"
c0044="bpy.ops.mesh.separate('INVOKE_DEFAULT')"
c0045="bpy.ops.bsmax.connectpoly('INVOKE_DEFAULT')"
c0046="bpy.ops.wm.tool_set_by_id(name='builtin.extrude_region')"
c0047="bpy.ops.wm.tool_set_by_id(name='builtin.bevel')"
c0048="bpy.ops.mesh.remove_doubles(threshold=1.0,use_unselected=False)"
c0049="bpy.ops.bsmax.createshapefromedge('INVOKE_DEFAULT')"
c0050="bpy.ops.mesh.dissolve_faces('INVOKE_DEFAULT')"
c0051="bpy.ops.bsmax.detachmesh('INVOKE_DEFAULT')"
c0052="bpy.ops.wm.tool_set_by_id(name='builtin.extrude_region')"
c0053="bpy.ops.wm.tool_set_by_id(name='builtin.inset_faces')"
c0054="bpy.ops.mesh.flip_normals('INVOKE_DEFAULT')"
c0055="bpy.ops.curve.chamfer('INVOKE_DEFAULT')"
c0056="bpy.ops.curve.chamfer('INVOKE_DEFAULT',fillet=True)"
c0057="bpy.context.object.data.type='POINT'"
c0058="bpy.context.object.data.type='SUN'"
c0059="bpy.context.object.data.type='SPOT'"
c0060="bpy.context.object.data.type='AREA'"
c0061="bpy.context.object.data.use_shadow="
c0062="bpy.ops.bsmax.createsphere('INVOKE_DEFAULT')"
c0063="bpy.ops.bsmax.createbox('INVOKE_DEFAULT')"
c0064="bpy.ops.bsmax.createcylinder('INVOKE_DEFAULT')"
c0065="bpy.ops.bsmax.createplane('INVOKE_DEFAULT')"
c0066="bpy.ops.bsmax.createline('INVOKE_DEFAULT')"
c0067="bpy.ops.bsmax.createcircle('INVOKE_DEFAULT')"
c0068="bpy.ops.bsmax.createrectangle('INVOKE_DEFAULT')"
c0069="bpy.ops.bsmax.createarc('INVOKE_DEFAULT')"
c0070="bpy.ops.view3d.view_axis(type='FRONT')"
c0071="bpy.ops.view3d.view_axis(type='BACK')"
c0072="bpy.ops.view3d.view_axis(type='TOP')"
c0073="bpy.ops.view3d.view_axis(type='BOTTOM')"
c0074="bpy.ops.view3d.view_axis(type='LEFT')"
c0075="bpy.ops.view3d.view_axis(type='RIGHT')"
c0076="bpy.ops.view3d.view_persportho('INVOKE_DEFAULT')"
c0077="bpy.ops.bsmax.setasactivecamera('INVOKE_DEFAULT')"
c0078="bpy.ops.bsmax.createcamerafromview('INVOKE_DEFAULT')"
c0079="bpy.ops.bsmax.setkeys('INVOKE_DEFAULT')"
c0080="bpy.ops.bsmax.setkeyfilters('INVOKE_DEFAULT')"
c0081="bpy.ops.bsmax.deleteselectedanimation('INVOKE_DEFAULT')"
c0082="bpy.ops.bsmax.coordinatesystem(coordsys='CURSOR')"
c0083="bpy.ops.bsmax.coordinatesystem(coordsys='LOCAL')"
c0084="bpy.ops.bsmax.coordinatesystem(coordsys='NORMAL')"
c0085="bpy.ops.bsmax.coordinatesystem(coordsys='GIMBAL')"
c0086="bpy.ops.bsmax.coordinatesystem(coordsys='VIEW')"
c0087="bpy.ops.bsmax.coordinatesystem(coordsys='GLOBAL')"
c0088="bpy.context.scene.tool_settings.snap_elements={'INCREMENT'}"
c0089="bpy.context.scene.tool_settings.snap_elements={'VERTEX'}"
c0090="bpy.context.scene.tool_settings.snap_elements={'VOLUME'}"
c0091="bpy.context.scene.tool_settings.snap_elements={'EDGE'}"
c0092="bpy.context.scene.tool_settings.snap_elements={'FACE'}"
c0093="bpy.context.scene.tool_settings.snap_target='CLOSEST'"
c0094="bpy.context.scene.tool_settings.snap_target='CENTER'"
c0095="bpy.context.scene.tool_settings.snap_target='MEDIAN'"
c0096="bpy.context.scene.tool_settings.snap_target='ACTIVE'"
c0097="bpy.ops.render.render('INVOKE_DEFAULT')"
c0098="bpy.ops.bsmax.attachmesh('INVOKE_DEFAULT')"
c0099="bpy.ops.bsmax.attachlistmesh('INVOKE_DEFAULT')"
c0100="bpy.ops.object.quick_smoke('INVOKE_DEFAULT')"
c0101="bpy.ops.object.quick_fur('INVOKE_DEFAULT')"
c0102="bpy.ops.object.quick_explode('INVOKE_DEFAULT')"
c0103="bpy.ops.object.quick_fluid('INVOKE_DEFAULT')"
c0104="bpy.ops.object.origin_set(type='GEOMETRY_ORIGIN',center='MEDIAN')"
c0105="bpy.ops.object.origin_set(type='ORIGIN_GEOMETRY',center='MEDIAN')"
c0106="bpy.ops.object.origin_set(type='ORIGIN_CURSOR',center='MEDIAN')"
c0107="bpy.ops.object.origin_set(type='ORIGIN_CENTER_OF_VOLUME',center='MEDIAN')"
c0108="bpy.ops.object.origin_set(type='ORIGIN_CENTER_OF_MASS',center='MEDIAN')"
c0109="bpy.ops.wm.tool_set_by_id(name='builtin.cursor')"
c0110="bpy.context.scene.tool_settings.use_snap_translate="
c0111="bpy.context.scene.tool_settings.use_snap_rotate="
c0112="bpy.context.scene.tool_settings.use_snap_scale="
c0113="bpy.context.scene.render.engine='BLENDER_EEVEE'"
c0114="bpy.context.scene.render.engine='BLENDER_WORKBENCH'"
c0115="bpy.context.scene.render.engine='CYCLES'"
c0116="bpy.context.scene.eevee.use_gtao=not bpy.context.scene.eevee.use_gtao"
c0117="bpy.context.scene.eevee.use_bloom=not bpy.context.scene.eevee.use_bloom "
c0118="bpy.context.scene.eevee.use_ssr=not bpy.context.scene.eevee.use_ssr"
c0119="bpy.context.scene.eevee.use_motion_blur=not bpy.context.scene.eevee.use_motion_blur"
c0120="bpy.context.scene.render.use_simplify=not bpy.context.scene.render.use_simplify"
c0121="bpy.context.scene.render.use_freestyle=not bpy.context.scene.render.use_freestyle"
c0122="bpy.context.scene.cycles_curves.use_curves=not bpy.context.scene.cycles_curves.use_curves"
c0123="bpy.context.scene.shading.show_backface_culling=not bpy.context.scene.shading.show_backface_culling"
c0124="bpy.context.scene.render.use_motion_blur=not bpy.context.scene.render.use_motion_blur"
c0125="bpy.context.scene.shading.show_xray=not bpy.context.scene.shading.show_xray"
c0126="bpy.context.scene.shading.show_shadows=not bpy.context.scene.shading.show_shadows"
c0127="bpy.context.scene.shading.show_cavity=not bpy.context.scene.shading.show_cavity"
c0128="bpy.context.scene.shading.use_dof=not bpy.context.scene.shading.use_dof"
c0129="bpy.context.scene.shading.show_object_outline=not bpy.context.scene.shading.show_object_outline"
c0130="bpy.ops.bsmax.targetweld('INVOKE_DEFAULT')"
c0131="bpy.ops.bsmax.maketargetcamera('INVOKE_DEFAULT')"
c0132="bpy.ops.bsmax.makefreecamera('INVOKE_DEFAULT')"
c0133="bpy.ops.bsmax.searchcamera('INVOKE_DEFAULT')"
c0134="bpy.ops.bsmax.createextrudeshape('INVOKE_DEFAULT')"
c0135="bpy.ops.bsmax.removeisolatedgeometry('INVOKE_DEFAULT')"
c0136="bpy.ops.bsmax.setlocalcoordinposemode('INVOKE_DEFAULT')"
c0137="bpy.ops.bsmax.lockcameratoviewtoggle('INVOKE_DEFAULT')"
c0138="bpy.ops.bsmax.selectactivecamera('INVOKE_DEFAULT',selcam=True,seltrg=False)"
c0139="bpy.ops.bsmax.selectactivecamera('INVOKE_DEFAULT',selcam=False,seltrg=True)"
c0140="bpy.ops.bsmax.selectactivecamera('INVOKE_DEFAULT',selcam=True,seltrg=True)"
c0141="bpy.ops.bsmax.maketargetlight('INVOKE_DEFAULT')"
c0142="bpy.ops.bsmax.makefreelight('INVOKE_DEFAULT')"
c0143="bpy.ops.mesh.bridge_edge_loops('INVOKE_DEFAULT',twist_offset=0)"
c0144="bpy.ops.bsmax.alignselectedobjects('INVOKE_DEFAULT')"
c0145="bpy.ops.curve.chamfer('INVOKE_DEFAULT',typein=True)"
c0146="bpy.ops.curve.chamfer('INVOKE_DEFAULT',fillet=True,typein=True)"
c0147="bpy.ops.bsmax.selecttarget('INVOKE_DEFAULT')"
c0148="bpy.ops.bmax.bonedevide('INVOKE_DEFAULT')"
c0149="bpy.ops.bmax.bonedevide('INVOKE_DEFAULT',typein=True)"
c0150="bpy.ops.bmax.armaturebonetype('INVOKE_DEFAULT',mode='OCTAHEDRAL')"
c0151="bpy.ops.bmax.armaturebonetype('INVOKE_DEFAULT',mode='STICK')"
c0152="bpy.ops.bmax.armaturebonetype('INVOKE_DEFAULT',mode='BBONE')"
c0153="bpy.ops.bmax.armaturebonetype('INVOKE_DEFAULT',mode='ENVELOPE')"
c0154="bpy.ops.bmax.armaturebonetype('INVOKE_DEFAULT',mode='WIRE')"
c0155="bpy.ops.bsmax.freezetransform('INVOKE_DEFAULT')"
c0156="bpy.ops.bsmax.freezerotation('INVOKE_DEFAULT')"
c0157="bpy.ops.bsmax.transformtozero('INVOKE_DEFAULT')"
c0158="bpy.ops.bsmax.rotationtozero('INVOKE_DEFAULT')"
c0159="bpy.ops.curve.dividplus('INVOKE_DEFAULT',typein=True)"
c0160="bpy.ops.curve.switch_direction('INVOKE_DEFAULT')"
c0161="bpy.ops.curve.makefirst('INVOKE_DEFAULT')"
c0162="bpy.context.space_data.lock_camera = not bpy.context.space_data.lock_camera"
c0163="bpy.context.space_data.lock_cursor = not bpy.context.space_data.lock_cursor"
c0164=""
c0165=""
c0166=""
c0167=""
c0168=""
c0169=""
c0170=""